---
name: 💡 Feature Request
description: Suggest an idea or improvement for this project
title: "[FEATURE] <title>"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. You can attach images or screenshots if applicable.
      placeholder: I'm always frustrated when I do ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen..
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context?
      description: |
        Links? References? Anything that will give us more context about this request!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
