---
name: Build and Push Latest Docker Image

on: # yamllint disable
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
      - ".gitignore"
      - ".markdownlint.yaml"
      - ".pre-commit-config.yaml"
      - ".yamllint.yml"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - ".github/ISSUE_TEMPLATE/"
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.12", "3.13"]  # List of all supported Python versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: amitkma/python-ffmpeg
          tags: ${{ matrix.python_version }}-slim

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.python_version }}/Dockerfile  # Adjust if needed
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
